### ISSUE TITLE
谢谢大佬 :"}

### ISSUE THREAD

**Issue by cs12110** [fangjian0423/springmvc-source-minibook#2]
看大佬的`blog`受益匪浅,特来感谢一下大佬.

谢谢大佬. :"}

**Comment by cs12110** [comment]
有一个小小的问题: `https://www.cnblogs.com/fangjian0423/p/servletContainer-tomcat-urlPattern.html#springmvc`

这篇文章里面,这里是不是有点问题?不是精确匹配到了吗?

![issue](https://user-images.githubusercontent.com/12764287/75641568-9dffc180-5c73-11ea-88ba-dd3233450544.jpg)

**Comment by fangjian0423** [comment]
😄
